language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
before_install: sudo apt-get install graphviz
install: "pip install -r -e requirements.txt"
script: python runAllTests.py
branches:
    only: master

