# ref: https://docs.travis-ci.com/user/languages/python
sudo: required

language: python
python:
  - "3.7"
  #- "3.5-dev" # 3.5 development branch
  #- "nightly" # points to the latest development branch e.g. 3.6-dev

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-compose
  - pip install -U pytest
  - pip install -U codecov

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r testing/requirements.txt

before_script:
  - docker swarm init
  - ./walkoff.sh up -bdy

# command to run tests
script:
  - pytest testing/api/

after_script:
  - codecov
  - docker stack services ci
  - docker stack ps ci
  - ./walkoff.sh down -cy