language: python
os:
    - linux
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
before_script:
  - python scripts/generate_certificates.py
script:
  - coverage run -m unittest tests.suites.workflow_suite
  - coverage run --append -m unittest tests.suites.execution_suite
  - coverage run --append -m unittest tests.suites.case_suite
  - coverage run --append -m unittest tests.suites.server_suite
  - coverage run --append -m unittest tests.suites.interface_suite
  - coverage combine
  - coverage report
branches:
    only: 
      - master
      - development

