language: python
os:
    - linux
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
before_script:
  - python generate_certificates.py
script:
  - coverage run test.py
  - coverage combine
  - coverage report
branches:
    only: 
      - master
      - development

