version: '3.5'
services:
  umpire:
    command: python -m umpire.umpire
      # Valid flags for umpire:
      # --log-level
      # --disable-worker-autoscale
      # --disable-app-autoscale
      # --disable-worker-autoheal
      # --disable-app-autoheal
      # --debug (asyncio debug)
    image: 127.0.0.1:5000/umpire:latest
    build:
      context: ./
      dockerfile: umpire/Dockerfile
    networks:
      - walkoff_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./apps:/app/apps
    deploy:
      placement:
        constraints: [node.role==manager]
    depends_on:
      - walkoff_redis
      - registry
    secrets:
      - walkoff_encryption_key
    configs:
      - common_env.yml

  registry:
    image: registry:2
    deploy:
      placement:
        constraints: [node.role==manager]
    ports:
      - 5000:5000
    networks:
      - walkoff_default
    # The commented lines are needed to enable auth on the custom registry
    #    environment:
    #      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    #      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    #      REGISTRY_AUTH: htpasswd
    #      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    #      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      #      - ./data/config.yml:/etc/docker/registry/config.yml
      - ./data/registry:/var/lib/registry
  #      - /var/lib/boot2docker:/certs
  #      - /var/lib/boot2docker/auth:/auth

  api_gateway:
    #    ports:
    #    - "8080:8080"
    image: "127.0.0.1:5000/api_gateway:latest"
    build:
      context: ./
      dockerfile: ./api_gateway/Dockerfile
    networks:
      - walkoff_default
    stop_signal: SIGINT
    stop_grace_period: 30s
    secrets:
      - walkoff_encryption_key
    configs:
      - common_env.yml
    depends_on:
      - redis
      - postgres
  #    volumes:
  #      - ./api_gateway/client/:/app/api_gateway/client

  walkoff_redis:
    container_name: walkoff_redis
    image: "redis"
#    ports:
#      - 6379:6379
    networks:
      - walkoff_default
    command: redis-server --port 6379
  #    volumes:
  #      - /var/lib/boot2docker/redis:/data

  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_USER=walkoff"
      - "POSTGRES_PASSWORD=walkoff"
#    ports:
#      - 5432:5432
    deploy:
      placement:
        constraints: [node.role==manager]
    networks:
      - walkoff_default
  #    volumes:
  #      - /var/lib/boot2docker/postgresql/data:/var/lib/postgresql/data
  #
  #elasticsearch:
  #    image: "docker.elastic.co/elasticsearch/elasticsearch:7.0.0"
  #    healthcheck:
  #      test: ["CMD", "curl", "-sf", "http://localhost:9200/_cat/health"]
  #    environment:
  #      - "discovery.type=single-node"
  #    ports:
  #      - 9200:9200
  #      - 9300:9300
  #    networks:
  #      - walkoff_default

  portainer:
    image: "portainer/portainer"
#    ports:
#      - 9020:9000
    networks:
      - walkoff_default
    deploy:
      placement:
        constraints: [node.role==manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  #      - portainer_data:/data portainer/portainer

  #  kibana:
  #    image: "docker.elastic.co/kibana/kibana:7.0.0"
  #    ports:
  #      - 5601:5601
  #    networks:
  #      - walkoff_default
  #    depends_on:
  #      - elasticsearch

  nginx:
    image: 'bitnami/nginx:latest'
    ports:
      - '8080:8080'
      - '8081:8081' # Uncomment for unsecure HTTP access to API Gateway
    volumes:
      - ./nginx/walkoff.conf:/opt/bitnami/nginx/conf/server_blocks/walkoff.conf:ro
      - ./nginx/cert.pem:/opt/bitnami/nginx/conf/cert.pem:ro
      - ./nginx/key.pem:/opt/bitnami/nginx/conf/key.pem:ro
    depends_on:
      - api_gateway

configs:
  common_env.yml:
    file: ./data/config.yml

secrets:
  walkoff_encryption_key:
    external: true

networks:
  walkoff_default:
    driver: overlay
    name: walkoff_default
    attachable: true
