Playbook:
    type: object
    required: [name]
    properties:
      name:
        type: string

AllPlaybooksOverview:
  type: array
  items:
    $ref: '#/definitions/PlaybookOverview'

PlaybookOverview:
  type: object
  description: Stripped-down view of a playbook
  required: [name, workflows]
  properties:
    name:
      type: string
      description: name of the playbook
    workflows:
      description: workflows inside of this playbook
      type: array
      items:
        $ref: '#/definitions/WorkflowDescription'

WorkflowDescription:
  type: object
  required: [name, uid]
  properties:
    name:
      type: string
      description: name of the workflow
    uid:
      type: string
      description: UID of the workflow

UpdatePlaybook:
    type: object
    required: [name]
    properties:
      name:
        type: string
      new_name:
        type: string

Workflow:
  type: object
  required: [name]
  description: A workflow object
  additionalProperties: false
  properties:
    name:
      description: The name of the workflow. Composed of both its enclosing playbook and its own name
      type: string
      example: HelloWorldWorkflow
    steps:
      description: The steps defined in this workflow.
      type: array
      items:
        $ref: "#/definitions/DisplayStep"
    next_steps:
      description: The possible next steps
      type: array
      items:
        $ref: '#/definitions/NextStep'
    start:
      description: UID of the starting step
      type: string
      default: start
      example: step1
    accumulated_risk:
      description: The risk which has been accumulated as this workflow has been executed
      type: number
      example: 0.43
      readOnly: true

AddWorkflow:
    type: object
    required: [name]
    properties:
      name:
        type: string

WorkflowUpdate:
    type: object
    required: [name]
    properties:
      name:
        type: string
      new_name:
        type: string

CopyWorkflow:
    type: object
    properties:
      playbook:
        type: string
      workflow:
        type: string

WorkflowId:
  type: object
  required: [id]
  properties:
    id:
      type: string
      description: 32-byte hexidecimal string representing the ID of the workflow
      readOnly: true

Step:
  type: object
  required: [name, action, app]
  description: Encapsulation of executing an action in an app
  additionalProperties: false
  properties:
    uid:
      description: UID of this step
      type: string
      x-nullable: true
    name:
      description: Name of the step
      type: string
      example: step1
    action:
      description: The action the step will take
      type: string
      example: pause
    app:
      description: The app to which the action belongs
      type: string
      example: CyberAnalytics
    triggers:
      description: String representation of a list of Trigger objects
      type: array
      items:
        $ref: '#/definitions/Condition'
    device:
      description: Name of the device to use
      type: string
      example: server4
    risk:
      description: risk associated with this step failing
      type: number
      default: 0
      example: 20
    arguments:
      description: The input arguments to the action
      type: array
      items:
        $ref: '#/definitions/Argument'
    output:
      description: The output of the step after it has been executed
      type: string
      example: result_from_step
    widgets:
      description: The widgets to which this app should send its output
      type: array
      items:
        type: object
        required: [app, name]
        properties:
          app:
            description: Name of the app
            type: string
            example: HelloWorld
          widget:
            description: Name of the widget
            type: string
            example: testWidget
    position:
      description:  position of the step onthe workflow editor
      type: object
      required: [x, y]
      properties:
        x:
          description: x position
          type: number
          example: 443.22
        y:
          description: y position
          type: number
          example: -12.036

DisplayStep:
  type: object
  description: Encapsulation of executing an action in an app
  properties:
    name:
      description: Name of the step
      type: string
      example: step1
    action:
      description: The action the step will take
      type: string
      example: pause
    app:
      description: The app to which the action belongs
      type: string
      example: CyberAnalytics
    triggers:
      description: String representation of a list of Trigger objects
      type: array
      items:
        $ref: '#/definitions/Condition'
    device:
      description: Name of the device to use
      type: string
      example: server4
    risk:
      description: risk associated with this step failing
      type: number
      default: 0
      example: 20
    arguments:
      description: The input arguments to the action
      type: array
      items:
        $ref: '#/definitions/Argument'
    widgets:
      description: The widgets to which this app should send its output
      type: array
      items:
        type: object
        required: [app, name]
        properties:
          app:
            description: Name of the app
            type: string
            example: HelloWorld
          widget:
            description: Name of the widget
            type: string
            example: testWidget
    position:
      description:  position of the step onthe workflow editor
      type: object
      required: [x, y]
      properties:
        x:
          description: x position
          type: number
          example: 443.22
        y:
          description: y position
          type: number
          example: -12.036

NextStep:
  type: object
  required: [source_uid, destination_uid]
  description: Encapsualtion of a list of possible steps to take and conditionals required to be met before taking that step
  additionalProperties: false
  properties:
    source_uid:
      description: The source Step UID for this NextStep
      type: string
    destination_uid:
      description: The destination Step UID for this NextStep, if the conditions evaluate to True
      type: string
    uid:
      description: UID of this step
      type: string
      x-nullable: true
    priority:
      description: The priority for this NextStep, which will be compared to other NextSteps with the same source_uid Step, ascending, i.e. 1 is the highest priority.
      type: integer
    status:
      description: The status return code to use
      type: string
      example: Success
    conditions:
      description: List of conditions to evaluate
      type: array
      items:
        $ref: '#/definitions/Condition'

Condition:
  type: object
  required: [action]
  description: Takes data and checks it against a condition given by its action Optionally filters the data before checking.
  additionalProperties: false
  properties:
    uid:
      description: UID of this step
      type: string
      x-nullable: true
    app:
      description: The app to which the conditon belongs
      type: string
      example: Utilities
    action:
      description: The action encapsulated by this condition
      type: string
      example: regMatch
    arguments:
      description: The inputs to the condition
      type: array
      items:
        $ref: '#/definitions/Argument'
    transforms:
      description: transforms for the data before passing it into the condition
      type: array
      items:
        $ref: '#/definitions/Transform'

Transform:
  type: object
  required: [action]
  description: Filters or otherwise transforms the data given to it
  additionalProperties: false
  properties:
    uid:
      description: UID of this step
      type: string
      x-nullable: true
    app:
      description: The app to which the transform belongs
      type: string
      example: Utilities
    action:
      description: The action encapsulated by this transform
      type: string
      example: count
    args:
      description: The inputs to the transform
      type: array
      items:
        $ref: '#/definitions/Argument'

Argument:
  type: object
  required: [name]
  description: Object used for passing an argument into actions
  properties:
    name:
      type: string
      example: regex
    value:
      description: The value of the argument
      example: WALK(.*)
    reference:
      description: The UID of the step whose output should be used
      type: string
    selection:
      description: >-
        The path to a subsection of the output of the step to use. For example [1, "a"] would use the second element
        of a list, and the "a" field of that object.
      type: array
      items:
        type: [string, integer]

