---
namespace: default
config:
  worker: 
    name: walkoff-worker
    replicas: 5
  app:
    name: walkoff-app
    zmq_service: walkoff-app-internal
    zmq_results_port: 5556
    zmq_comm_port: 5557
    http_service: walkoff-app-external
    http_backend_port: 8080
  storage:
    name: walkoff-storage
    size: 5Gi
  certs:
    issuer_name: walkoff-ca-issuer
  ingress:
    name: walkoff-ingress
secrets:
  certs: walkoff-cert-secret
  zmq_private: walkoff-zmq-private-keys
  zmq_public: walkoff-zmq-public-keys
resources:
  execution_db:
    db_type: postgresql
    service_name: execution-db-postgresql
    secret_name: walkoff-postgres-execution-secret
    username: walkoff
    password_key: postgres-password
  walkoff_db:
    db_type: postgresql
    service_name: walkoff-db-postgresql
    secret_name: walkoff-postgres-secret
    username: walkoff
    password_key: postgres-password
  redis:
    service_name: walkoff-redis-master
    port: 6379 
    secret_name: walkoff-redis-secret
    password_key: redis-password
images:
  worker: registry.hub.docker.com/walkoffcyber/walkoff:workerv1
  app: registry.hub.docker.com/walkoffcyber/walkoff:appv1