---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.storage.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.config.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.worker.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.config.worker.replicas }}
  selector:
    matchLabels:
      run: {{ .Values.config.worker.name }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        run: {{ .Values.config.worker.name }}
    spec:
      volumes:
      - name: cert-volume
        secret:
          secretName: {{ .Values.secrets.certs }}
      - name: zmq-private
        secret:
          secretName: {{ .Values.secrets.zmq_private }}
      - name: zmq-public
        secret:
          secretName: {{ .Values.secrets.zmq_public }}
      - name: walkoff-storage
        persistentVolumeClaim:
          claimName: {{ .Values.config.storage.name }}
      containers:
      - name: {{ .Values.config.worker.name }}
        image: {{ .Values.images.worker }}
        volumeMounts:
        - name: cert-volume
          readOnly: true
          mountPath: "/app/walkoff/certs"
        - name: zmq-private
          readOnly: true
          mountPath: "/app/walkoff/certs/private_keys"
        - name: zmq-public
          readOnly: true
          mountPath: "/app/walkoff/certs/public_keys"
        - name: walkoff-storage
          mountPath: "/app/walkoff/commonstorage"
        env:
          - name: EXECUTION_DB_USERNAME
            value: {{ .Values.resources.execution_db.username }}
          - name: EXECUTION_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.resources.execution_db.secret_name }}
                key: {{ .Values.resources.execution_db.password_key }}
          - name: WALKOFF_DB_USERNAME
            value: {{ .Values.resources.walkoff_db.username }}
          - name: WALKOFF_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.resources.walkoff_db.secret_name }}
                key: {{ .Values.resources.walkoff_db.password_key }}
          - name: WALKOFF_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.resources.redis.secret_name }}
                key: {{ .Values.resources.redis.password_key }}
          - name: CACHE
            value: "{\"type\": \"redis\",\"host\": \"{{ .Values.resources.redis.service_name }}\",\"port\": {{ .Values.resources.redis.port }}}"
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "{{ .Values.config.http_backend_port }}"
          - name: ZMQ_RESULTS_ADDRESS
            value: "tcp://{{ .Values.config.app.zmq_service }}:{{ .Values.config.zmq_results_port }}"
          - name: ZMQ_COMMUNICATION_ADDRESS
            value: "tcp://{{ .Values.config.app.zmq_service }}:{{ .Values.config.zmq_comm_port }}"
          - name: SEPARATE_WORKERS
            value: "true"
          - name: WALKOFF_DB_TYPE 
            value: "{{ .Values.resources.walkoff_db.db_type }}"
          - name: EXECUTION_DB_TYPE
            value: "{{ .Values.resources.execution_db.db_type }}"
          - name: DB_PATH 
            value: "walkoff"
          - name: EXECUTION_DB_PATH
            value: "execution"
          - name: WALKOFF_DB_HOST
            value: "{{ .Values.resources.walkoff_db.service_name }}"
          - name: EXECUTION_DB_HOST
            value: "{{ .Values.resources.execution_db.service_name }}"
          - name: KEYS_PATH
            value: "./certs"
          - name: CERTIFICATE_PATH
            value: "./certs/none.crt"
          - name: PRIVATE_KEY_PATH
            value: "./certs/none.key"
          - name: ZMQ_PRIVATE_KEYS_PATH
            value: "./certs/private_keys"
          - name: ZMQ_PUBLIC_KEYS_PATH
            value: "./certs/public_keys"
          - name: SQLALCHEMY_DATABASE_URI
            value: "{{ .Values.resources.walkoff_db.db_type }}://walkoff:walkoff@{{ .Values.resources.walkoff_db.service_name }}/walkoff"
          - name: NUMBER_PROCESSES
            value: "1"
        # command:
        # - "sleep"
        # - "36000"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.config.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.config.app.name }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        run: {{ .Values.config.app.name }}
    spec:
      volumes:
      - name: cert-volume
        secret:
          secretName: {{ .Values.secrets.certs }}
      - name: zmq-private
        secret:
          secretName: {{ .Values.secrets.zmq_private }}
      - name: zmq-public
        secret:
          secretName: {{ .Values.secrets.zmq_public }}
      - name: walkoff-storage
        persistentVolumeClaim:
          claimName: {{ .Values.config.storage.name }}
      containers:
      - name: {{ .Values.config.app.name }}
        image: {{ .Values.images.app }}
        volumeMounts:
        - name: cert-volume
          readOnly: true
          mountPath: "/app/walkoff/certs"
        - name: zmq-private
          readOnly: true
          mountPath: "/app/walkoff/certs/private_keys"
        - name: zmq-public
          readOnly: true
          mountPath: "/app/walkoff/certs/public_keys"
        - name: walkoff-storage
          mountPath: "/app/walkoff/commonstorage"
        env:
          - name: EXECUTION_DB_USERNAME
            value: {{ .Values.resources.execution_db.username }}
          - name: EXECUTION_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.resources.execution_db.secret_name }}
                key: {{ .Values.resources.execution_db.password_key }}
          - name: WALKOFF_DB_USERNAME
            value: {{ .Values.resources.walkoff_db.username }}
          - name: WALKOFF_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.resources.walkoff_db.secret_name }}
                key: {{ .Values.resources.walkoff_db.password_key }}
          - name: WALKOFF_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.resources.redis.secret_name }}
                key: {{ .Values.resources.redis.password_key }}
          - name: CACHE
            value: "{\"type\": \"redis\",\"host\": \"{{ .Values.resources.redis.service_name }}\",\"port\": {{ .Values.resources.redis.port }}}"
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "{{ .Values.config.http_backend_port }}"
          - name: ZMQ_RESULTS_ADDRESS
            value: "tcp://0.0.0.0:{{ .Values.config.zmq_results_port }}"
          - name: ZMQ_COMMUNICATION_ADDRESS
            value: "tcp://0.0.0.0:{{ .Values.config.zmq_comm_port }}"
          - name: SEPARATE_WORKERS
            value: "true"
          - name: WALKOFF_DB_TYPE 
            value: "{{ .Values.resources.walkoff_db.db_type }}"
          - name: EXECUTION_DB_TYPE
            value: "{{ .Values.resources.execution_db.db_type }}"
          - name: DB_PATH 
            value: "walkoff"
          - name: EXECUTION_DB_PATH
            value: "execution"
          - name: WALKOFF_DB_HOST
            value: "{{ .Values.resources.walkoff_db.service_name }}"
          - name: EXECUTION_DB_HOST
            value: "{{ .Values.resources.execution_db.service_name }}"
          - name: KEYS_PATH
            value: "./certs"
          - name: CERTIFICATE_PATH
            value: "./certs/none.crt"
          - name: PRIVATE_KEY_PATH
            value: "./certs/none.key"
          - name: ZMQ_PRIVATE_KEYS_PATH
            value: "./certs/private_keys"
          - name: ZMQ_PUBLIC_KEYS_PATH
            value: "./certs/public_keys"
          - name: SQLALCHEMY_DATABASE_URI
            value: "{{ .Values.resources.walkoff_db.db_type }}://walkoff:walkoff@{{ .Values.resources.walkoff_db.service_name }}/walkoff"
          - name: NUMBER_PROCESSES
            value: "1"
        ports:
        - containerPort: {{ .Values.config.http_backend_port }}
          name: http
        - containerPort: {{ .Values.config.zmq_results_port }}
          name: zmq-results
        - containerPort: {{ .Values.config.zmq_comm_port }}
          name: zmq-comm
        # command:
        # - "sleep"
        # - "36000"
