apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.config.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: {{ .Values.config.certs.issuer_name }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - secretName: {{ .Values.secrets.certs }}
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.config.app.http_service }}
          servicePort: {{ .Values.config.app.http_backend_port }}