---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.app.zmq_service }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Values.config.app.name }}
spec:
  ports:
  - port: {{ .Values.config.app.zmq_results_port }}
    name: zmq-results
  - port: {{ .Values.config.app.zmq_comm_port }}
    name: zmq-comm
  selector:
    run: {{ .Values.config.app.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.app.http_service }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Values.config.app.name }}
spec:
  ports:
  - port: {{ .Values.config.app.http_backend_port }}
    name: http
  selector:
    run: {{ .Values.config.app.name }}