apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: walkoff-cert
  namespace: walkoff
spec:
  secretName: walkoff-cert-secret
  issuerRef:
    name: ca-issuer
    kind: Issuer
  dnsNames:
  - walkofftest.eastus.cloudapp.azure.com
