apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: walkoff-cert
  namespace: default
spec:
  commonName: walkoff
  issuerRef:
    kind: Issuer
    name: walkoff-ca-issuer
  organization:
  - WALKOFF
  secretName: walkoff-cert-secret
