version: '3.4'
services:
  power_shell:
    build:
      context: .
      dockerfile: Dockerfile
#    image: walkoff_registry:5000/walkoff_app_HelloWorld-v1-0
    env_file:
      - env.txt
    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: none
      placement:
        constraints: [node.role==manager]
    restart: "no"
