'/configuration/{key}':
  get:
    tags:
      - Configuration
    summary: Get a configuration key
    description: ''
    operationId: server.endpoints.configuration.config_values
    parameters:
      - name: key
        in: path
        description: 'The configuration key '
        required: true
        type: string
    produces:
      - application/json
    responses:
      '200':
        description: Okay
/configuration/set:
  post:
    tags:
      - Configuration
    summary: Edits a configuration value
    description: ''
    operationId: server.endpoints.configuration.set_configuration
    consumes:
      - multipart/form-data
    produces:
      - application/json
#    parameters:
#      - name: key
#        in: formData
#        description: The name that needs to be fetched.
#        required: true
#        type: string
    responses:
      '200':
        description: Okay