version: '3.5'
services:
  registry:
    restart: always
    image: registry:2
#    deploy:
#      placement:
#        constraints: [node.role==manager]
    ports:
      - 5000:5000
    networks:
      - walkoff_default
    # The commented lines are needed to enable auth on the custom registry
    #    environment:
    #      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    #      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    #      REGISTRY_AUTH: htpasswd
    #      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    #      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
#    volumes:
      #      - ./data/config.yml:/etc/docker/registry/config.yml
#      - ./data/registry:/var/lib/registry
  #      - /var/lib/boot2docker:/certs
  #      - /var/lib/boot2docker/auth:/auth

  redis:
    container_name: redis
    image: "redis"
    ports:
      - 6379:6379
    networks:
      - walkoff_default
    #    volumes:
    #      - /var/lib/boot2docker/redis:/data

  postgres:
    container_name: postgres
    image: "postgres"
    environment:
      - "POSTGRES_USER=walkoff"
      - "POSTGRES_PASSWORD=walkoff"
    ports:
      - 5432:5432
    deploy:
      placement:
        constraints: [node.role==manager]
    networks:
      - walkoff_default
#    volumes:
#      - /var/lib/boot2docker/postgresql/data:/var/lib/postgresql/data

secrets:
  encryption_key:
    external: true

networks:
  walkoff_default:
    driver: overlay
    name: walkoff_default