version: '3.5'
services:
  resource_registry:
    image: registry:2
    networks:
      - walkoff_default
#    deploy:
#      placement:
#        constraints: [node.role==manager]
    ports:
      - 5000:5000

#    The commented lines are needed to enable auth on the custom registry
#    environment:
#      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
#      REGISTRY_AUTH: htpasswd
#      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
#      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
#    volumes:
#      - ./data/config.yml:/etc/docker/registry/config.yml
#      - ./data/registry:/var/lib/registry
#      - /var/lib/boot2docker:/certs
#      - /var/lib/boot2docker/auth:/auth

  resource_redis:
    image: "redis"
    networks:
      - walkoff_default
    command: redis-server --port 6379
#    volumes:
#      - /path/to/persistent/dir/redis:/data

  resource_postgres:
    image: "postgres"
    networks:
      - walkoff_default
    environment:
      - "POSTGRES_USER=walkoff"
      - "POSTGRES_PASSWORD=walkoff"
    deploy:
      placement:
        constraints: [node.role==manager]
#    volumes:
#      - /path/to/persistent/dir/postgresql/data:/var/lib/postgresql/data

  resource_portainer:
    image: "portainer/portainer"
    networks:
      - walkoff_default
    deploy:
      placement:
        constraints: [node.role==manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data portainer/portainer

configs:
  common_env.yml:
    file: ./data/config.yml

secrets:
  encryption_key:
    external: true

networks:
  walkoff_default:
    driver: overlay
    name: walkoff_default