apiVersion: v1
kind: Service
metadata:
  name: postgres-casedb
  namespace: walkoff
spec:
  ports:
  - name: postgres-casedb
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-casedb

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-casedb
  namespace: walkoff
spec:
  replicas: 1
  template:
    metadata:
      namespace: walkoff
      labels:
        app: postgres-casedb
    spec:
      containers:
        - name: postgres-casedb
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              value: walkoff
            - name: POSTGRES_PASSWORD
              value: walkoff
            - name: POSTGRES_DB
              value: walkoff
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          emptyDir: {}