apiVersion: apps/v1
kind: Deployment
metadata:
  name: walkoff-worker
  namespace: walkoff
spec:
  replicas: 5
  selector:
    matchLabels:
      run: walkoff-worker
  template:
    metadata:
      namespace: walkoff
      labels:
        run: walkoff-worker
    spec:
      containers:
      - name: walkoff-worker
        image: x.azurecr.io/walkoff-worker:vy
        env:
          - name: WALKOFF_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: walkoff-db-secrets
                key: WALKOFF_DB_USERNAME
          - name: WALKOFF_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: walkoff-db-secrets
                key: WALKOFF_DB_PASSWORD
#        command:
#        - "sleep"
#        - "36000"
      imagePullSecrets:
      - name: aks