apiVersion: apps/v1
kind: Deployment
metadata:
  name: walkoff-worker
  namespace: walkoff
spec:
  replicas: 5
  selector:
    matchLabels:
      run: walkoff-worker
  template:
    metadata:
      namespace: walkoff
      labels:
        run: walkoff-worker
    spec:
      volumes:
      - name: cert-volume
        secret:
          secretName: walkoff-cert-secret
      - name: zmq-private
        secret:
          secretName: zmq-private-keys
      - name: zmq-public
        secret:
          secretName: zmq-public-keys
      - name: walkoff-storage
        persistentVolumeClaim:
          claimName: walkoff-storage
      containers:
      - name: walkoff-worker
        image: walkoffacr.azurecr.io/walkoff-worker:old
        volumeMounts:
        - name: cert-volume
          readOnly: true
          mountPath: "/app/walkoff/certs"
        - name: zmq-private
          readOnly: true
          mountPath: "/app/walkoff/certs/private_keys"
        - name: zmq-public
          readOnly: true
          mountPath: "/app/walkoff/certs/public_keys"
        - name: walkoff-storage
          mountPath: "/app/walkoff/commonstorage"
        env:
          - name: WALKOFF_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: walkoff-db-secrets
                key: WALKOFF_DB_USERNAME
          - name: WALKOFF_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: walkoff-db-secrets
                key: WALKOFF_DB_PASSWORD
        command:
        - "sleep"
        - "36000"
      imagePullSecrets:
      - name: aks