apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: walkoff-cert
  namespace: default
spec:
  dnsNames:
  - walkoffhelmtest.eastus.cloudapp.azure.com
  issuerRef:
    kind: Issuer
    name: ca-issuer
  secretName: null
