Configuration:
    type: object
    description: The configuration
    additionalProperties : false
    properties:
      workflows_path:
        type: string
        description: The path to the workflows
      db_path:
        type: string
        description: The path to the primary WALKOFF database
      case_db_path:
        type: string
        description: The path to the case database
      log_config_path:
        type: string
        description: The path to the logging configuration
      host:
        type: string
        description: The server's host URL
      port:
        type: integer
        description: The server's port
        minimum: 0
        maximum: 65535
      walkoff_db_type:
        type: string
        description: The type of database used by the primary WALKOFF database
        enum: [sqlite, mysql, postgresql, oracle, mssql]
      case_db_type:
        type: string
        description: The type of database used by the case database
        enum: [sqlite, mysql, postgresql, oracle, mssql]
      clear_case_db_on_startup:
        type: boolean
        description: Should the case database be cleared upon a server restart?
      number_processes:
        type: integer
        minimum: 1
        description: Number of worker processes which can execute workflows
      access_token_duration:
        type: number
        minimum: 1
        description: Time (in minutes) to allow an access token to persist. Should greater than the duration of the refresh token
      refresh_token_duration:
        type: number
        minimum: 1
        description: Time (in days) to allow a refresh token to persist. Should greater than the duration of the refresh token
      zmq_requests_address:
        type: string
        description: The IP address and port of the ZMQ requests server. Do not change unless necessary.
      zmq_results_address:
        type: string
        description: The IP address and port of the ZMQ results server. Do not change unless necessary.
      zmq_communication_address:
        type: string
        description: The IP address and port of the ZMQ communication server. Do not change unless necessary.
