CreatePlaybook:
    type: object
    required: [name]
    additionalProperties: false
    properties:
      name:
        type: string
      workflows:
        type: array
        items:
          $ref: '#/definitions/CreateWorkflow'

Playbook:
    type: object
    required: [id]
    additionalProperties: false
    properties:
      id:
        $ref: '#/definitions/Uid'
      name:
        type: string
      workflows:
        type: array
        items:
          $ref: '#/definitions/Workflow'

CreateWorkflow:
  type: object
  required: [name]
  description: A workflow object
  additionalProperties: false
  properties:
    name:
      description: The name of the workflow. Composed of both its enclosing playbook and its own name
      type: string
      example: HelloWorldWorkflow
    start:
      description: ID of the starting action
      $ref: '#/definitions/Uid'
    actions:
      description: The actions defined in this workflow.
      type: array
      items:
        $ref: "#/definitions/Action"
    branches:
      description: The possible branches
      type: array
      items:
        $ref: '#/definitions/Branch'
    playbook_id:
      description: Only used when copying a workflow to a different playbook
      $ref: '#/definitions/Uid'

Workflow:
  type: object
  required: [id, name, start]
  description: A workflow object
  additionalProperties: false
  properties:
    id:
      $ref: '#/definitions/Uid'
    name:
      description: The name of the workflow. Composed of both its enclosing playbook and its own name
      type: string
      example: HelloWorldWorkflow
    start:
      description: ID of the starting action
      $ref: '#/definitions/Uid'
    actions:
      description: The actions defined in this workflow.
      type: array
      items:
        $ref: "#/definitions/Action"
    branches:
      description: The possible branches
      type: array
      items:
        $ref: '#/definitions/Branch'

Action:
  type: object
  required: [id, app_name, action_name, name]
  description: Encapsulation of executing an action in an app.
  additionalProperties: false
  properties:
    id:
      $ref: '#/definitions/Uid'
      description: The ID of the object. If updating a workflow and the Action object already exists, ID is required. Otherwise, this ID must be UUID4.
    app_name:
      description: The app to which the action belongs
      type: string
      example: CyberAnalytics
    action_name:
      description: The action the action will take
      type: string
      example: pause
    name:
      description: Name of the action
      type: string
      example: action1
    device_id:
      description: ID of the device to use
      type: integer
      example: 42
    arguments:
      description: The input arguments to the action
      type: array
      items:
        $ref: '#/definitions/Argument'
    trigger:
      description: The trigger condition
      $ref: '#/definitions/ConditionalExpression'
    position:
      description: Position object representing various fields of the position of the Action in the playbook editor.
      $ref: '#/definitions/Position'

Branch:
  type: object
  required: [source_id, destination_id]
  description: Encapsualtion of a list of possible actions to take and conditionals required to be met before taking that action
  additionalProperties: false
  properties:
    id:
      $ref: '#/definitions/Uid'
      description: The ID of the object. If updating a workflow and the Branch object already exists, ID is required. Otherwise, do not include it.
    source_id:
      description: The source Action ID for this Branch
      $ref: '#/definitions/Uid'
    destination_id:
      description: The destination Action ID for this Branch, if the conditions evaluate to True
      $ref: '#/definitions/Uid'
    priority:
      description: The priority for this Branch, which will be compared to other Branches with the same source_uid Action, ascending, i.e. 1 is the highest priority.
      type: integer
    status:
      description: The status return code to use
      type: string
      example: Success
    condition:
      description: List of condition to evaluate
      $ref: '#/definitions/ConditionalExpression'


ConditionalExpression:
  type: object
  description: Object which encapsulates Boolean logic
  properties:
    operator:
      type: string
      description: The operation to use which on the conditions
      enum: [and, or, xor]
      default: and
    is_inverted:
      description: Should the result of this condition be inverted? For example if the condition would return True, then invert it to return False.
      type: boolean
      default: false
    conditions:
      description: Base conditions to evaluate.
      type: array
      items:
        $ref: '#/definitions/Condition'
    child_expressions:
      description: Sub-expressions to evaluate.
      type: array
      items:
        $ref: '#/definitions/ConditionalExpression'


Argument:
  type: object
  required: [name]
  description: Object used for passing an argument into actions. Either reference or value must be selected.
  minProperties: 2
  additionalProperties: false
  properties:
    id:
      type: integer
      description: The ID of the object. If updating a workflow and the Argument object already exists, ID is required. Otherwise, do not include it.
    name:
      type: string
      example: regex
    value:
      description: The value of the argument
      example: WALK(.*)
    reference:
      $ref: '#/definitions/Uid'
      description: The ID of the action whose output should be used
    selection:
      description: >-
        The path to a subsection of the output of the action to use. For example [1, "a"] would use the second element
        of a list, and the "a" field of that object.
      type: array
      items:
        type: [string, integer]

Condition:
  type: object
  required: [app_name, action_name]
  description: Takes data and checks it against a condition given by its action Optionally filters the data before checking.
  additionalProperties: false
  properties:
    id:
      $ref: '#/definitions/Uid'
      description: The ID of the object. If updating a workflow and the Condition object already exists, ID is required. Otherwise, do not include it.
    app_name:
      description: The app to which the conditon belongs
      type: string
      example: Utilities
    action_name:
      description: The action encapsulated by this condition
      type: string
      example: regMatch
    arguments:
      description: The inputs to the condition
      type: array
      items:
        $ref: '#/definitions/Argument'
    is_inverted:
      description: Should the result of this condition be inverted? For example if the condition would return True, then invert it to return False.
      type: boolean
      default: false
    transforms:
      description: transforms for the data before passing it into the condition
      type: array
      items:
        $ref: '#/definitions/Transform'

Transform:
  type: object
  required: [app_name, action_name]
  description: Filters or otherwise transforms the data given to it
  additionalProperties: false
  properties:
    id:
      $ref: '#/definitions/Uid'
      description: The ID of the object. If updating a workflow and the Transform object already exists, ID is required. Otherwise, do not include it.
    app_name:
      description: The app to which the transform belongs
      type: string
      example: Utilities
    action_name:
      description: The action encapsulated by this transform
      type: string
      example: count
    arguments:
      description: The inputs to the transform
      type: array
      items:
        $ref: '#/definitions/Argument'

Position:
  type: object
  required: [x, y]
  description: Various specifications for how the Action is displayed in the playbook editor
  additionalProperties: false
  properties:
    id:
      type: integer
      description: The ID of the object. If updating a workflow and the Position object already exists, ID is required. Otherwise, do not include it.
    x:
      type: number
      description: The X coordinate for the Action
    y:
      type: number
      description: The Y coordinate for the Action

CopyWorkflow:
    type: object
    properties:
      playbook_id:
        $ref: '#/definitions/Uid'
      workflow_name:
        type: string

UpdatePlaybook:
  type: object
  required: [id]
  additionalProperties: false
  properties:
    id:
      $ref: '#/definitions/Uid'
    name:
      type: string
      description: The new name of the playbook
